name: Integration Tests
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]
    branches:
      - 'master'
      - 'release/**'
jobs:
  integration-tests:
    strategy:
      matrix:
        magento_version: [2.3.7-p3, 2.4.2]
    name: Magento 2 Integration Tests
    if: ${{!contains(github.head_ref, 'release/')}}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_SQL_TO_RUN: 'GRANT ALL ON *.* TO "root"@"%";'
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - if: matrix.magento_version == '2.3.7-p3'
        name: M2 Integration Tests on ${{ matrix.magento_version }}
        uses: MultiSafepay/github-actions-m2/magento-integration-tests/7.3@with-coverage-support
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
            GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
            CURRENT_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
            module_name: MultiSafepay_ConnectCore
            composer_name: multisafepay/magento2-core
            ce_version: '${{ matrix.magento_version }}'
            magento_pre_install_script: .github/workflows/magento-integration-tests-pre-install.sh
      - if: matrix.magento_version == '2.4.2'
        name: M2 Integration Tests on ${{ matrix.magento_version }}
        uses: MultiSafepay/github-actions-m2/magento-integration-tests/7.4@with-coverage-support
        env:
            MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
            MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
            GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
            CURRENT_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
            module_name: MultiSafepay_ConnectCore
            composer_name: multisafepay/magento2-core
            ce_version: '${{ matrix.magento_version }}'
            phpunit_file: './phpunit.xml'
            magento_pre_install_script: .github/workflows/magento-integration-tests-pre-install.sh
            magento_post_install_script: .github/workflows/magento-integration-tests-post-install.sh
      - name: Send clover to codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -R .
